### ISSUE TITLE
Crash while loading (version 3.1.6 with postgres 9.6)

### ISSUE THREAD

**Issue by nobleread** [ossc-db/pg_bulkload#85]
Crash while loading (version 3.1.6 with postgres 9.6).

Getting a crash loading a table inside IndexSpoolEnd():

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `postgres: atoms task [local] SELECT '.
Program terminated with signal 11, Segmentation fault.
#0 compare_indextuple (itup1=itup1@entry=0x7f63adfe1db0, itup2=itup2@entry=0x2063f68, entry=entry@entry=0x207b038, keysz=keysz@entry=1, tupdes=tupdes@entry=0x7f64e4ab5778, hasnull=hasnull@entry=0x7fff55907bee "") at pg_btree.c:890
#0 compare_indextuple (itup1=itup1@entry=0x7f63adfe1db0, itup2=itup2@entry=0x2063f68, entry=entry@entry=0x207b038, keysz=keysz@entry=1, tupdes=tupdes@entry=0x7f64e4ab5778, hasnull=hasnull@entry=0x7fff55907bee "") at pg_btree.c:890
#1 0x00007f63b2bacdac in _bt_mergeload (heapRel=0x7f64e4ab08f0, btspool2=0x7fff55907c20, btspool=0x2039c68, wstate=0x7fff55907bf0, self=0x20377b8) at pg_btree.c:559
0000002 _bt_mergebuild (btspool=0x2039c68, self=0x20377b8) at pg_btree.c:436
0000003 IndexSpoolEnd (self=0x20377b8) at pg_btree.c:256
0000004 SpoolerClose (self=self@entry=0x20377b8) at pg_btree.c:166
0000005 0x00007f63b2bb40e9 in BufferedWriterClose (self=0x2037718, onError=<optimized out>) at writer_buffered.c:114
0000006 0x00007f63b2bb2d1b in WriterClose (self=self@entry=0x2037718, onError=onError@entry=0 '\000') at writer.c:121
0000007 0x00007f63b2bae0ec in pg_bulkload (fcinfo=0x7fff55908950) at pg_bulkload.c:398
0000008 0x00000000005bdcb5 in ExecMakeTableFunctionResult (funcexpr=0x202de08, econtext=0x202d698, argContext=<optimized out>, expectedDesc=0x202f488, randomAccess=0 '\000') at execQual.c:2211
0000009 0x00000000005d35d3 in FunctionNext (node=node@entry=0x202d588) at nodeFunctionscan.c:94
0000010 0x00000000005bfc74 in ExecScanFetch (recheckMtd=0x5d3310 <FunctionRecheck>, accessMtd=0x5d3320 <FunctionNext>, node=0x202d588) at execScan.c:95
0000011 ExecScan (node=node@entry=0x202d588, accessMtd=accessMtd@entry=0x5d3320 <FunctionNext>, recheckMtd=recheckMtd@entry=0x5d3310 <FunctionRecheck>) at execScan.c:145
#12 0x00000000005d360f in ExecFunctionScan (node=node@entry=0x202d588) at nodeFunctionscan.c:268
0000013 0x00000000005b8f68 in ExecProcNode (node=node@entry=0x202d588) at execProcnode.c:449
0000014 0x00000000005b53b7 in ExecutePlan (dest=0x1ffa478, direction=<optimized out>, numberTuples=0, sendTuples=1 '\001', operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x202d588, estate=0x202d478) at execMain.c:1567
0000015 standard_ExecutorRun (queryDesc=0x1f5bca8, direction=<optimized out>, count=0) at execMain.c:339
0000016 0x00007f64d9db3fad in pgss_ExecutorRun (queryDesc=0x1f5bca8, direction=ForwardScanDirection, count=0) at pg_stat_statements.c:877
0000017 0x00007f64d9bae545 in explain_ExecutorRun (queryDesc=0x1f5bca8, direction=ForwardScanDirection, count=0) at auto_explain.c:279
0000018 0x00000000006c1dd7 in PortalRunSelect (portal=portal@entry=0x1f2d1b8, forward=forward@entry=1 '\001', count=0, count@entry=9223372036854775807, dest=dest@entry=0x1ffa478) at pquery.c:948
0000019 0x00000000006c313f in PortalRun (portal=portal@entry=0x1f2d1b8, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=1 '\001', dest=dest@entry=0x1ffa478, altdest=altdest@entry=0x1ffa478, completionTag=completionTag@entry=0x7fff55909370 "") at pquery.c:789
#20 0x00000000006c0711 in exec_execute_message (max_rows=9223372036854775807, portal_name=0x1ffa068 "") at postgres.c:1992
0000021 PostgresMain (argc=<optimized out>, argv=argv@entry=0x1f5fe38, dbname=0x1f5fcf0 "task", username=<optimized out>) at postgres.c:4164
0000022 0x000000000046d85b in BackendRun (port=0x1f5d4b0) at postmaster.c:4339
#23 BackendStartup (port=0x1f5d4b0) at postmaster.c:4013
#24 ServerLoop () at postmaster.c:1722
0000025 0x0000000000666b36 in PostmasterMain (argc=argc@entry=5, argv=argv@entry=0x1f0dad0) at postmaster.c:1330
0000026 0x000000000046e33a in main (argc=5, argv=0x1f0dad0) at main.c:228
```

The table contains multiple complex indexes, which I suspect is the place where it crashes:

```
CREATE INDEX idxom_25419334_1 ON public.om_acct2_custom USING btree (phone, areacode);
CREATE INDEX idxom_25419334_3 ON public.om_acct2_custom USING btree (branch_num);
CREATE UNIQUE INDEX idxom_25419334_4 ON public.om_acct2_custom USING btree (score_account_id);
CREATE UNIQUE INDEX sidxom_25419334_6 ON public.om_acct2_custom USING btree (record_id);
```

**Comment by nobleread** [comment]
We verified dropping all indexes, then bulk loading, then re-creating all indexes is an effective workaround for this issue.
